name: m2-install-actions
on: [push]
jobs:
  magento2-install:
    runs-on: ubuntu-latest
    name: 'magento isntall & push'
    steps:
      - uses: actions/checkout@v2
      
      - name: Deployer Get composer.lock from server
        uses: qlicks/deployer-action@master
        env: 
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}