name: m2-install-actions
on: [push]
jobs:
  magento2-install:
    runs-on: ubuntu-latest
    name: 'magento isntall & push'
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
      
      - name: Deploy to the Server - AWS EC2 - via SSH
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: "ec2-34-216-180-142.us-west-2.compute.amazonaws.com"
          username: "ubuntu"
          target: "/var/www/magento245"
      
      