name: m2-install-actions
on: [push]
jobs:
  magento2-install:
    runs-on: ubuntu-latest
    name: 'magento isntall & push'
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
      
      - name: Deploy to the Server - AWS EC2 - via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: "ec2-34-216-180-142.us-west-2.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/magento245"